sudo: required
dist: trusty

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libgsl0-dev ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gsl ; fi

script:
  - autoreconf -fi
  - ./configure
  - make
  - make check
  - make distcheck

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always
