sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran-5
      env: CC='gcc-5' CXX='g++-5' FC='gfortran-5' CFLAGS='-DNRUNS=100000000'
    - os: osx
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      env: CC='gcc-5' CXX='g++-5' FC='gfortran-5' CFLAGS='-DNRUNS=100000000' BREW='gsl homebrew/versions/gcc5'
    - os: osx
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' CFLAGS='-DNRUNS=100000000' BREW='gsl homebrew/versions/gcc6'

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get --yes --force-yes update && sudo apt-get --yes --force-yes install libgsl0-dev ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install ${BREW} ; fi


script:
  - autoreconf -fi
  - ./configure
  - make
  - make check
  - make distcheck

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always
