sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - gfortran-4.8
      env: CC='gcc-4.8' CXX='g++-4.8' FC='gfortran-4.8' CFLAGS='-DNRUNS=100000000'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
      env: CC='gcc-4.9' CXX='g++-4.9' FC='gfortran-4.9' CFLAGS='-DNRUNS=100000000'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran-5
      env: CC='gcc-5' CXX='g++-5' FC='gfortran-5' CFLAGS='-DNRUNS=100000000'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' CFLAGS='-DNRUNS=100000000'
    - os: osx
      osx_image: beta-xcode6.3
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      osx_image: xcode6.4
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      osx_image: xcode7
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      osx_image: xcode7.1
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      osx_image: xcode7.2
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      osx_image: xcode7.3
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      osx_image: xcode8
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      env: CC='gcc-4.8' CXX='g++-4.8' FC='gfortran-4.8' CFLAGS='-DNRUNS=100000000' BREW='gsl homebrew/versions/gcc48'
    - os: osx
      env: CC='gcc-4.9' CXX='g++-4.9' FC='gfortran-4.9' CFLAGS='-DNRUNS=100000000' BREW='gsl homebrew/versions/gcc49'
    - os: osx
      env: CC='gcc-5' CXX='g++-5' FC='gfortran-5' CFLAGS='-DNRUNS=100000000' BREW='gsl homebrew/versions/gcc5'
    - os: osx
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' CFLAGS='-DNRUNS=100000000' BREW='gsl homebrew/versions/gcc6'
  allow_failures:
    - os: osx
      osx_image: beta-xcode6.1
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'
    - os: osx
      osx_image: beta-xcode6.2
      env: CC='clang' CXX='clang++' CFLAGS='-DNRUNS=100000000' BREW='gsl'

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get --yes --force-yes update && sudo apt-get --yes --force-yes install libgsl0-dev ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew uninstall --force gcc carthage && brew update && brew upgrade && brew install ${BREW} ; fi


script:
  - autoreconf -fi
  - ./configure
  - make
  - make check
  - make distcheck

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always
